### ISSUE TITLE
Refactor the `Chart` class to avoid `Canvas` inheritence

### ISSUE THREAD

**Issue by saroad2** [beeware/toga-chart#21]
**Is your feature request related to a problem? Please describe.**
This is a continuation of discussion made in beeware/toga-chart#20.

Right now, `Canvas.redraw` is used as an internal method of `Canvas` which is used after adding a new drawing element to it. It basically means that "a new element was added and we need to redraw the canvas to the window".

However, For the `Chart` class we want to use `redraw` in a different way: Assuming that a new element was added to the chart, one might want to call `redraw` manually to update the `Chart`.

When trying to use `Chart.redraw` as the second option, it causes an infinite loop as one can see in the linked PR.

**Describe the solution you'd like**
There are 2 possible solutions:
1. Add a new method called `Chart.update` that updates the chart **manually** (on call) based on new changes.
2. Refactor `Chart` to no longer inherit from `Canvas` so it could redefine the method `redraw`.

**Comment by saroad2** [comment]
Hey @freakboy3742 ,

I changed the title and description of the issue.

I would love if you could take the time and explain how you would refactor the `Chart` class to no longer inherit from `Canvas`.
It seems like `Chart` would no longer inherit from `Widget` and will be a sort of wrapper to the `Canvas` class. Am I correct?

**Comment by freakboy3742** [comment]
Close, but not quite. `Chart` will still inherit from `Widget`, as it needs to be a widget from the perspective of Toga to be added to a layout. However, it won't inherit from `Canvas` or any `FigureCanvasBase` - the `Canvas` and `FigureCanvasBase` will be *attributes* of the Widget. In that respect it will be a "wrapper"; the Toga Chart widget will be composed of the base widgets, rather than inheriting from the base widgets.

**Comment by saroad2** [comment]
This might be problematic:

If `Chart` is a widget, when you set the `style` attribute of `Chart` you should actually set the `style` attribute of the `Canvas` underneath. This might be problematic to solve.

I thought that a better solution should look like the following:

```python
def startup():
    canvas = toga.Canvas(style=Pack(flex=1))
    chart = toga_chart.Chart(canvas=canvas, on_draw=on_draw)

    content = toga.Box(
        children = [canvas]
    )
    main_window.content = content
```

Now it is clear that the `Canvas` is the actual widget and `Chart` is a help function that draws a figure into the `Canvas`.

Moreover, we can say that if a canvas was not presented in the constructor of `Chart` it will create a new one. So the example should also be written like:

```python
def startup():
    chart = toga_chart.Chart(on_draw=on_draw)  # Creates a new Canvas as attribute
    chart.canvas.style.flex = 1

    content = toga.Box(
        children = [chart.canvas]
    )
    main_window.content = content
```

**Comment by freakboy3742** [comment]
The approach you've describe could be made to work, but it's not really making Chart a widget in the sense that I'm describing. What you've described here - is some sort of weird container object where the end user needs to know about the internal implementation of Chart. 

What I'm suggesting is that toga.Chart should actually *be* a widget - it's external API surface is the same as a widget. If you set the style of the chart, it is is applied to the chart; and when you add the chart to a layout, you add the *chart* to the layout. The fact that the Chart is backed by a toga.Canvas is an implementation detail - but not one the user needs to know about.

One way to do this would be to have the Chart create a Canvas instance and store it as a member - but make `Chart._impl` be the `Canvas._impl` instance. This means most of the *internal* operations will be performed directly on the Canvas instance - but the public interface that users see won't have most of the Canvas API entry points. 

You can then make the Canvas API one that makes sense from the perspective of end-users, proxying those calls to the Canvas instance as necessary.
