### ISSUE TITLE
Sphinx 7.2 dropped support for Python 3.8

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga-chart#33]
### Describe the bug

Sphinx 7.2 dropped support for Python 3.8. Documentation builds on Python 3.8 will now fail.

This won't affect CI, but it might affect users building locally.

### Steps to reproduce

`tox -r -e docs` in a Python 3.8 environment.

### Expected behavior

The tox docs target should build without error on Python 3.8

### Environment

- Python version: 3.8

### Logs

```

```

### Additional context

The fix for this is to add a Python version qualifier to the docs extra dependencies in `setup.cfg.`

**Comment by garthk** [comment]
Reproduced.

```plain
$ tox
…
ERROR: No matching distribution found for sphinx==7.2.2
```

**Comment by garthk** [comment]
Working on the [requirement specifiers](https://pip.pypa.io/en/stable/reference/requirement-specifiers/#requirement-specifiers)… it's going to look something like this:
```diff
diff --git a/setup.cfg b/setup.cfg
index 4a9cdce..aff8813 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -56,7 +56,8 @@ dev =
 docs =
     furo == 2023.8.19
     pyenchant == 3.2.2
-    sphinx == 7.2.2
+    sphinx == 7.2.2 ; python_version >= '3.9'
+    sphinx == 7.* ; python_version < '3.9'
     sphinx_tabs == 3.4.1
     sphinx-autobuild == 2021.3.14
     sphinx-copybutton == 0.5.2
```
That works, but I need to look in tox' target virtual environment to figure out which version it plucked.

**Comment by garthk** [comment]
```plain
$ .tox/docs/bin/pip freeze | grep inx      
Sphinx==7.1.2
```
Gotcha. And, after 
```plain
$ tox -r -e docs,py38
…
docs: OK ✔ in 18.18 seconds
```
