### ISSUE TITLE
Python 3.12 builds are failing CI runs

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga-chart#34]
### Describe the bug

Python 3.12 builds are currently failing on CI because of a Matplotlib incompatibility.

### Steps to reproduce

See CI build results - e.g. https://github.com/beeware/toga-chart/actions/runs/5920155562

### Expected behavior

CI should pass cleanly.

As an interim measure, CI builds should not fail *outright* - 3.12 builds should be considered experimental, and not fail the overall builds.

### Environment

CI

### Logs

```

```

**Comment by ahonnecke** [comment]
Context: https://github.com/matplotlib/matplotlib/issues/26161

**Comment by rmartin16** [comment]
`toga-chart` installs on my machine for Python 3.12. The release of `numpy==1.26.0` probably resolved this issue. CI also ran [successfully](https://github.com/beeware/toga-chart/actions/runs/6686249666/job/18165462900) recently for 3.12.
