### ISSUE TITLE
PRs fail flake8 in CI for already existing code.

### ISSUE THREAD

**Issue by ahonnecke** [beeware/toga-chart#62]
### Describe the bug

![image](https://github.com/beeware/toga-chart/assets/419355/ae1555f2-779e-4544-8b2c-87d96d8adb97)

### Steps to reproduce

1. Open a PR

### Expected behavior

The PR fails if the dev has introduced errors.

### Environment

- Operating System:
- Linux
- Python version:
- N/A

### Logs

```
 [INFO] This may take a few minutes...
check toml...............................................................Passed
check yaml...............................................................Passed
check for case conflicts.................................................Passed
check docstring is first.................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
isort....................................................................Passed
pyupgrade................................................................Passed
black....................................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

docs/conf.py:123:20: E231 missing whitespace after ':'
docs/conf.py:125:21: E231 missing whitespace after ':'

ensure-changelog.........................................................Failed
- hook id: ensure-changelog
- exit code: 3
```

### Additional context

FWIW, this only occurs in CI.  pre-commit works locally (ubuntu)

**Comment by rmartin16** [comment]
Only occurs for Python 3.12. Seems like `flake8==6.0.0` isn't compatible. Since the [`pre-commit-update`](https://github.com/beeware/toga-chart/actions/workflows/pre-commit-update.yml) workflow hasn't been working, the hooks are out of date. https://github.com/beeware/toga-chart/pull/57 is trying to fix this.

Nonetheless, using `flake8==6.1.0` should fix this for Python 3.12.
